apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/stephmen/docker-next
  creationTimestamp: "2020-07-21T00:10:25Z"
  generation: 2
  labels:
    app: docker-next
    app.kubernetes.io/component: docker-next
    app.kubernetes.io/instance: docker-next
    app.kubernetes.io/part-of: docker-nextjs-app
  name: docker-next
  namespace: docker-nextjs
  resourceVersion: "5901102"
  selfLink: /apis/apps.openshift.io/v1/namespaces/docker-nextjs/deploymentconfigs/docker-next
  uid: 934d91ec-cae6-11ea-aac9-0a580a80018f
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: docker-next
    deploymentconfig: docker-next
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-next
        deploymentconfig: docker-next
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/docker-nextjs/docker-next@sha256:d83542db855f9fdddd1c089bdee5366fb83dc630bd0ae60de593e74f371b5690
        imagePullPolicy: Always
        name: docker-next
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumeMounts:
        - name: configs
          mountPath: /app
      volumes:
      - name: configs
        configMap:
          name: vol-config-tweetor-api
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - docker-next
      from:
        kind: ImageStreamTag
        name: docker-next:latest
        namespace: docker-nextjs
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/docker-nextjs/docker-next@sha256:d83542db855f9fdddd1c089bdee5366fb83dc630bd0ae60de593e74f371b5690
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-21T01:07:17Z"
    lastUpdateTime: "2020-07-21T01:07:17Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-21T01:07:18Z"
    lastUpdateTime: "2020-07-21T01:07:18Z"
    message: replication controller "docker-next-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
